# Generated by Django 3.2.13 on 2022-05-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailers_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Robinson Trailers Blog', max_length=250),
        ),
    ]
