# Generated by Django 3.2.13 on 2022-05-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailers_blog', '0002_post_title_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='forestry', max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(max_length=250),
        ),
    ]
